### ISSUE TITLE
Unable to import it as es6 module.

### ISSUE THREAD

**Issue by AnuragSinghTomarr** [Silviu-Marian/reedux#1]
hi its a nice wrapper to use.
Just had a issue cannot use it as es6 import

> import reedux from 'reedux';

like we do for other dependencies installed via npm.

**Comment by Silviu-Marian** [comment]
Hey, nice to meet you
Thanks for letting me know, it should be fixed now

`npm install reedux@0.0.12`

**Comment by AnuragSinghTomarr** [comment]
Thanks brother it worked. One doubt in the code below

> // now you can add a reducer
> reducer((customers, action) => {
>   switch(action.type) {
>     case 'addCustomer':
>       return [...customers, action.customerData];
>     case 'deleteCustomer': 
>       return [...customers.filter(customer => customer.id !== action.customerId)];
>     default:
>       return customers;
>   }
> });

here reducer((customers, action) => .....) in this customers is the initial state of that particular reducer which is loaded on demand.

**Comment by Silviu-Marian** [comment]
That's correct. `customers` will be an empty array initially, or whatever you specify when registering  `storePath`

**Comment by AnuragSinghTomarr** [comment]
Thanks bro will implemt this and will let you know. :+1:
