### ISSUE TITLE
Reedux removes any existing state

### ISSUE THREAD

**Issue by NathanGloyn** [Silviu-Marian/reedux#2]
When adding a new reducer using reedux any existing state in the store is removed which wasn't the expectation as the readme states 

>  requires no modifications to the existing project

If I create a store with state which is loaded when the app is loaded
`const store = createStore(reducer, { app: { user: {}}};`
state at this point is 
```
{
    app: {
        user: {}
    }
}
```

then later load more of the site using react-loadable and reedux to attach the reducer all my existing state is removed e.g. 
`const addReducer = addStorePath('test', { x: 0, y: 0 });`

I would expect state to look like:
```
{
    app: {
        user: {}
    },
    test: {
        x: 0,
        y: 0
    }
}
```
but instead the state is:
```
{
    test: {
        x: 0,
        y: 0
    }
}
```

If you add the following test to the reedux.spec.js you can see this in action as the test will fail:
```
 it('should preserve any existing store state', () => {
    const existingStore = createStore( s => s, { router: { location: { path: '/' } } });
    assert.equal(existingStore.getState().router.location.path, '/');

    const addStorePath = reedux(existingStore);
    const addReducer = addStorePath('test', { x: 0, y: 0 });
    
    assert.equal(existingStore.getState().router.location.path, '/');
    assert.equal(getState().test.x, 0);
  })
```

When looking into this I managed to keep the initial state but only by creating a store which had no state at all and then adding the initial state through reedux unfortunately this didn't work when trying to implement connected-react-router as internally its looking for state but not finding it.

**Comment by Silviu-Marian** [comment]
Nope. It's a problem. Let me check it out.

**Comment by NathanGloyn** [comment]
I saw you updated the package and the test was passing so I pulled down the new npm to try but still had a problem.

I've attached a [zip](https://github.com/Silviu-Marian/reedux/files/1457469/MinimalAppToRecreate.zip) with minimal app that recreates the issue.

Appreciate you looked at this quickly as for the actual application we are using this is a blocking issue

**Comment by Silviu-Marian** [comment]
Wanted to give a detailed explanation before announcing that it's fixed

I already opened a new bug to update the docs
This is purpose built for larger settings where it makes sense to start breaking things down, and creating a different store, managed exclusively through Reedux, made sense

I don't really fancy the idea of having two competing libraries managing the same store. It won't work
But if all you have **redux** and **reedux**, now you should be able to `reedux(store, reducer)` - in the app you sent, file `src/store.js`, last line

As for the for the `forth` route in the sample app, I'm afraid that's not very well set up
The quickest fix you can do is

```js
const loadFourth = Loadable({
  loader: () => new Promise(r => r(() => <div>test</div>)),
  loading() {
    return <span>Loading</span>
  }
});
```

I hope this helps.

**Comment by NathanGloyn** [comment]
Thanks for the feedback 👍
