### ISSUE TITLE
Redux-form integration

### ISSUE THREAD

**Issue by GOVYANSONG** [Silviu-Marian/reedux#5]
I have a component that is wrapped within a redux-form. I successfully added reducer dynamically. When I dispatched an action, it reached the intended reducer with correct payload and updated state correctly. As soon as the reducer finished, the same reducer received a @ @ redux-form/TOUCH action and state is reverted back to initial values. Does anyone witness this behavior?

**Comment by GOVYANSONG** [comment]
Apparently, it is a bit more complicated than i originally thought. In my environment, we use selector, redux-form, router, DEV tools, hot module reload among others. The only reliable way is to combine all reducers at root level. My observation may be off but so far it holds.

**Comment by Silviu-Marian** [comment]
can you provide a sample project? by the looks of it the only condition that must be met is that the `redux-form`'s reducer has to be brought in and loaded before any of it's related actions trigger.

**Comment by GOVYANSONG** [comment]
Hi Marian, thanks for the quick follow up. I appreciate the thoughts given to this library and it broadened my horizon. Some background, I was experimenting with visual studio's sample create react app project. I need a way to dynamically inject reducers. During my struggle, If memory serves me well, redux-form reducer is always specified statically along with routing in the root reducer. I will try to reproduce the issue tomorrow. During meantime, I have found a decent workaround inspired by logic-injectors npm package. Access to store instance is non issue since it is a HOC wrapping my component. It augments store object with injectedReducers property that holds reducer map instead of a weak map. The injection logic is the first argument to redux compose function for my component. The logic is invoked when router visits the path for my component.

**Comment by GOVYANSONG** [comment]
Hi Marian, I created a new project today and here are the details:

1. Setup

In Visual Studio 2017, created a ASP.NET Core Web application with React/Redux template;
I modified package.json to refer to required npm packages: "redux-form": "7.2.3", "reedux": "0.1.2";

2. Experiment

File ClientApp\store\index.ts: only change was to comment out Counter.reducer
============================
import * as WeatherForecasts from './WeatherForecasts';
import * as Counter from './Counter';
import { reducer as reduxFormReducer } from 'redux-form';

// The top-level state object
export interface ApplicationState {
    counter: Counter.CounterState;
    weatherForecasts: WeatherForecasts.WeatherForecastsState;
}

// Whenever an action is dispatched, Redux will update each top-level application state property using
// the reducer with the matching name. It's important that the names match exactly, and that the reducer
// acts on the corresponding ApplicationState property type.
export const reducers = {
    //counter: Counter.reducer,
    weatherForecasts: WeatherForecasts.reducer,
    form: reduxFormReducer
};

// This type can be used as a hint on action creators so that its 'dispatch' and 'getState' params are
// correctly typed to match your store.
export interface AppThunkAction<TAction> {
    (dispatch: (action: TAction) => void, getState: () => ApplicationState): void;
}
============================

File ClientApp\configureStore.ts: only change was to dynamically inject Counter.reducer
============================
import { createStore, applyMiddleware, compose, combineReducers, GenericStoreEnhancer, Store, StoreEnhancerStoreCreator, ReducersMapObject } from 'redux';
import thunk from 'redux-thunk';
import { routerReducer, routerMiddleware } from 'react-router-redux';
import * as StoreModule from './store';
import { ApplicationState, reducers } from './store';
import { History } from 'history';
import * as Counter from './store/Counter';
import reedux from 'reedux';

export default function configureStore(history: History, initialState?: ApplicationState) {
    // Build middleware. These are functions that can process the actions before they reach the store.
    const windowIfDefined = typeof window === 'undefined' ? null : window as any;
    // If devTools is installed, connect to it
    const devToolsExtension = windowIfDefined && windowIfDefined.devToolsExtension as () => GenericStoreEnhancer;
    const createStoreWithMiddleware = compose(
        applyMiddleware(thunk, routerMiddleware(history)),
        devToolsExtension ? devToolsExtension() : <S>(next: StoreEnhancerStoreCreator<S>) => next
    )(createStore);

    // Combine all reducers and instantiate the app-wide store instance
    const allReducers = buildRootReducer(reducers);
    const store = createStoreWithMiddleware(allReducers, initialState) as Store<ApplicationState>;

    const storePath = reedux(store);
    const myReducer = storePath('counter', { count: 0 });
    myReducer(Counter.reducer);

    // Enable Webpack hot module replacement for reducers
    if (module.hot) {
        module.hot.accept('./store', () => {
            const nextRootReducer = require<typeof StoreModule>('./store');
            store.replaceReducer(buildRootReducer(nextRootReducer.reducers));
        });
    }

    return store;
}

function buildRootReducer(allReducers: ReducersMapObject) {
    return combineReducers<ApplicationState>(Object.assign({}, allReducers, { routing: routerReducer }));
}
============================

File ClientApp\components\Counter.tsx
============================
import * as React from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { connect } from 'react-redux';
import { ApplicationState }  from '../store';
import * as CounterStore from '../store/Counter';
import * as WeatherForecasts from '../store/WeatherForecasts';
import { InjectedFormProps, Field, reduxForm, Form } from 'redux-form';

type CounterProps =
    CounterStore.CounterState
    & typeof CounterStore.actionCreators
    & RouteComponentProps<{}>;

type InjectedProps = InjectedFormProps<CounterProps, {}>;

class Counter extends React.Component<InjectedProps> {
    //
    constructor(props) {
        super(props);
    }

    // own submit function
    private onSubmit(values) {
        console.log(JSON.stringify(values));
    }

    public render() {
        const { handleSubmit, pristine, reset, submitting } = this.props;
        return <div>
            <Form onSubmit={handleSubmit(this.onSubmit)}>    
                <h1>Counter</h1>

                <p>This is a simple example of a React component.</p>

                <p>Current count: <strong>{ this.props.count }</strong></p>

                <button onClick={() => { this.props.increment() }}>Increment</button>
                <p><Field name="demo" component="input" type="text" /></p>
                <button type="submit" disabled={pristine || submitting}>Submit</button>
            </Form>
        </div>;
    }
}

//
const InitCounterFromState = reduxForm<InjectedProps>(
    {
        form: 'CounterFromState',
    } // a unique identifier for this form
)(Counter);

// Wire up the React component to the Redux store
export default connect(
    (state: ApplicationState) => state.counter, // Selects which state properties are merged into the component's props
    CounterStore.actionCreators                 // Selects which action creators are merged into the component's props
)(InitCounterFromState);
============================

3. Observations

* The reducer worked and counter was updated as expected
* But I can not enter in the input field of my redux-form component
* If I reverted back to static reducer in the index.ts, all behaved properly

**Comment by Silviu-Marian** [comment]
I didn't properly understand your last message.

Can you please ZIP this sample project and send it here?

**Comment by GOVYANSONG** [comment]
Hi Marian, I was not able to reproduce the exact issue originally reported. I will close it for now and update when more details become available. Thanks for the assistance.
